import { type Expert } from './types';

export const experts: Expert[] = [
  {
    id: '1',
    name: 'Dr. Evelyn Reed',
    title: 'Startup Fundraising Mentor',
    category: 'Business',
    rating: 4.9,
    reviewsCount: 124,
    skills: ['Fundraising', 'Pitch Decks', 'Venture Capital', 'Angel Investing'],
    avatarUrl: 'https://picsum.photos/seed/1/128/128',
    bio: 'Seasoned venture capitalist with over 15 years of experience helping startups secure funding. I can help you craft the perfect pitch and connect with the right investors.',
    expertise: 'Specializes in seed and Series A funding rounds for tech startups.',
    responseTime: 'Within 12 hours',
    userReviewsSummary: 'Highly rated for providing actionable advice and valuable connections.',
    tiers: [
      { id: 't1-1', title: 'Pitch Deck Review', description: 'Detailed feedback on your pitch deck.', price: 250 },
      { id: 't1-2', title: '30-Min Strategy Call', description: 'A quick call to discuss your fundraising strategy.', price: 500 },
      { id: 't1-3', title: 'Full Fundraising Support', description: 'Comprehensive support through your entire funding round.', price: 5000 },
    ],
    reviews: [
      { id: 'r1-1', author: 'Jane Doe', rating: 5, comment: 'Evelyn\'s advice was a game-changer for our seed round!', avatarUrl: 'https://picsum.photos/seed/101/40/40' },
      { id: 'r1-2', author: 'John Smith', rating: 5, comment: 'Invaluable insights and connections.', avatarUrl: 'https://picsum.photos/seed/102/40/40' },
    ],
  },
  {
    id: '2',
    name: 'Marcus Chen',
    title: 'Lead Product Designer',
    category: 'Design',
    rating: 4.8,
    reviewsCount: 88,
    skills: ['UI/UX Design', 'Figma', 'Prototyping', 'User Research'],
    avatarUrl: 'https://picsum.photos/seed/2/128/128',
    bio: 'I am a product designer with a passion for creating beautiful and intuitive user experiences. I have worked with clients from early-stage startups to Fortune 500 companies.',
    expertise: 'Expert in user-centered design methodologies and creating scalable design systems.',
    responseTime: 'Within 24 hours',
    userReviewsSummary: 'Praised for creativity, attention to detail, and delivering high-quality designs.',
    tiers: [
      { id: 't2-1', title: 'UI/UX Audit', description: 'A complete audit of your app\'s design.', price: 300 },
      { id: 't2-2', title: '1-Hour Design Consultation', description: 'Brainstorm and solve your design challenges.', price: 400 },
      { id: 't2-3', title: 'Landing Page Design', description: 'A high-converting landing page design in Figma.', price: 1500 },
    ],
    reviews: [
      { id: 'r2-1', author: 'Alice Johnson', rating: 5, comment: 'Marcus transformed our app! The new design is amazing.', avatarUrl: 'https://picsum.photos/seed/103/40/40' },
    ],
  },
  {
    id: '3',
    name: 'Aisha Khan',
    title: 'Senior Software Engineer',
    category: 'Software Development',
    rating: 5.0,
    reviewsCount: 212,
    skills: ['React', 'Node.js', 'TypeScript', 'AWS', 'Architecture'],
    avatarUrl: 'https://picsum.photos/seed/3/128/128',
    bio: 'Full-stack developer with a decade of experience building scalable web applications. I specialize in the MERN stack and cloud architecture on AWS.',
    expertise: 'Expert in building and scaling complex web applications. Proficient in React, Node.js, and cloud infrastructure.',
    responseTime: 'Within 8 hours',
    userReviewsSummary: 'Consistently receives top reviews for technical expertise, clear communication, and problem-solving skills.',
    tiers: [
      { id: 't3-1', title: 'Code Review Session', description: 'In-depth review of your codebase.', price: 200 },
      { id: 't3-2', title: '1-Hour Technical Call', description: 'Solve your toughest technical problems.', price: 450 },
      { id: 't3-3', title: 'Pair Programming Session', description: 'A 2-hour hands-on coding session.', price: 800 },
    ],
    reviews: [
      { id: 'r3-1', author: 'Bob Williams', rating: 5, comment: 'Aisha is a genius. Solved a problem we were stuck on for weeks.', avatarUrl: 'https://picsum.photos/seed/104/40/40' },
    ],
  },
  {
    id: '4',
    name: 'David Kim',
    title: 'Growth Marketing Expert',
    category: 'Marketing',
    rating: 4.7,
    reviewsCount: 95,
    skills: ['SEO', 'Content Marketing', 'PPC', 'Social Media'],
    avatarUrl: 'https://picsum.photos/seed/4/128/128',
    bio: 'I help businesses grow their online presence and acquire customers through data-driven marketing strategies.',
    expertise: 'Specializes in organic growth through SEO and content marketing for B2B SaaS companies.',
    responseTime: 'Within 48 hours',
    userReviewsSummary: 'Valued for strategic thinking and delivering measurable results in traffic and lead generation.',
    tiers: [
      { id: 't4-1', title: 'SEO Audit', description: 'A comprehensive audit of your website\'s SEO.', price: 400 },
      { id: 't4-2', title: 'Marketing Strategy Session', description: 'A 1-hour call to define your growth strategy.', price: 600 },
      { id: 't4-3', title: 'Monthly Marketing Retainer', description: 'Ongoing marketing support.', price: 3000 },
    ],
    reviews: [],
  },
  {
    id: '5',
    name: 'Sophia Rodriguez',
    title: 'Legal Counsel for Tech',
    category: 'Legal',
    rating: 4.9,
    reviewsCount: 76,
    skills: ['Contracts', 'Intellectual Property', 'Corporate Law', 'Privacy'],
    avatarUrl: 'https://picsum.photos/seed/5/128/128',
    bio: 'Experienced lawyer providing legal guidance to tech startups and entrepreneurs. I can help with everything from incorporation to IP protection.',
    expertise: 'Focuses on intellectual property and data privacy law for technology companies.',
    responseTime: 'Within 24 hours',
    userReviewsSummary: 'Appreciated for clear, concise legal advice that is easy for non-lawyers to understand.',
    tiers: [
        { id: 't5-1', title: 'Contract Review', description: 'Review of one legal document up to 10 pages.', price: 500 },
        { id: 't5-2', title: '1-Hour Legal Consultation', description: 'Discuss your legal questions and concerns.', price: 750 },
    ],
    reviews: [
        { id: 'r5-1', author: 'Michael Brown', rating: 5, comment: 'Sophia made the legal stuff so easy to understand. Highly recommend!', avatarUrl: 'https://picsum.photos/seed/105/40/40' }
    ],
  },
  {
    id: '6',
    name: 'Ben Carter',
    title: 'Career & Leadership Coach',
    category: 'Coaching',
    rating: 5.0,
    reviewsCount: 150,
    skills: ['Career Growth', 'Leadership', 'Interview Prep', 'Public Speaking'],
    avatarUrl: 'https://picsum.photos/seed/6/128/128',
    bio: 'I empower professionals to advance their careers and become effective leaders. With a background in HR and executive coaching, I provide tailored guidance to help you reach your goals.',
    expertise: 'Coaching for mid-to-senior level professionals in the tech industry looking to move into leadership roles.',
    responseTime: 'Within 10 hours',
    userReviewsSummary: 'Celebrated for his empathetic approach and ability to inspire confidence and real change in his clients.',
    tiers: [
        { id: 't6-1', title: 'Resume & LinkedIn Review', description: 'Optimize your professional profiles.', price: 150 },
        { id: 't6-2', title: 'Mock Interview Session', description: 'A 45-minute mock interview with feedback.', price: 350 },
        { id: 't6-3', title: 'Monthly Coaching Program', description: 'Four 1-hour sessions per month.', price: 2000 },
    ],
    reviews: [
        { id: 'r6-1', author: 'Emily Davis', rating: 5, comment: 'Ben helped me land my dream job! His coaching was invaluable.', avatarUrl: 'https://picsum.photos/seed/106/40/40' }
    ],
  },
];
